name: CI
on:
#  push:
#    branches:
#      - develop
#    paths-ignore:
#      - '**.md'
  # Dispatch or Manual triggers
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@d9336dac04dea2507a617466bc058a3def92b18b # v3

      - name: Set up JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4
        with:
          java-version: 17
          distribution: adopt

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@d9336dac04dea2507a617466bc058a3def92b18b # v3

      - name: Build app
        run: ./gradlew assembleDevPreview testDevPreviewUnitTest --stacktrace

      - name: Upload APK
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4
        with:
          name: Komikku-${{ github.sha }}.apk
          path: app/build/outputs/apk/dev/preview/app-dev-universal-preview.apk
          retention-days: 1
